on:
  push:
    branches: [main, dev]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read

name: CI

env:
  CLICOLOR: 1

jobs:
  check:
    name: Check
    runs-on: macos-latest
    env:
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate
        run: git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com/".insteadOf "https://github.com/"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  build:
    needs: check
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin

        - os: macos-latest
          TARGET: x86_64-apple-darwin

        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-gnu

        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate
      run:
        git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com/".insteadOf "https://github.com/"

    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    - name: setup node
      uses: actions/setup-node@v4
      with:
          node-version: lts/*

    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}
        override: true

    - name: install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit

    - name: install frontend dependencies
      run: yarn install --frozen-lockfile

    - uses: tauri-apps/tauri-action@v0
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
        releaseName: 'App v__VERSION__'
        releaseBody: 'See the assets to download this version and install.'
        releaseDraft: true
        prerelease: false
        args: --target ${{ matrix.TARGET }}

  # release:
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: [check, build]
  #   permissions:
  #     contents: write
  #     actions: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Authenticate
  #       run: git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com/".insteadOf "https://github.com/"

  #     - name: Generate changelog
  #       uses: orhun/git-cliff-action@v4
  #       id: git-cliff
  #       with:
  #         config: cliff.toml
  #         args: -vv --latest --strip header
  #       env:
  #         OUTPUT: CHANGELOG.md

  #     - name: Create Release with changelog
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         body: ${{ steps.git-cliff.outputs.content }}
  #         draft: false
  #         prerelease: false
  #         generate_release_notes: false
