name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CLICOLOR: 1


permissions:
  contents: read

jobs:
  test:
    name: Test Suite
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate
        run:
          git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com/".insteadOf "https://github.com/"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --all-features
        env:
          APP_ENV: test
